root -l -q 'PlotNtupleVariables_ll_DataDrivenComplex.C("m_vis","visible mass [GeV] ", "Events",0, 300, 20,true,false,false,true,"","em","")'
root -l -q 'PlotNtupleVariables_ll_DataDrivenComplex.C("mll","Z legs visible mass [GeV] ", "Events",60, 120, 10,true,false,false,true,"","em","")'
root -l -q 'PlotNtupleVariables_ll_DataDrivenComplex.C("pt_1","pT_1 [GeV] ", "Events",0, 200, 10,true,false,false,true,"","em","")'
root -l -q 'PlotNtupleVariables_ll_DataDrivenComplex.C("pt_2","pT_2 [GeV] ", "Events",0, 150, 10,true,false,false,true,"","em","")'
root -l -q 'PlotNtupleVariables_ll_DataDrivenComplex.C("pt_3","pT_3 [GeV] ", "Events",0, 200, 10,true,false,false,true,"","em","")'
root -l -q 'PlotNtupleVariables_ll_DataDrivenComplex.C("pt_4","pT_4 [GeV] ", "Events",0, 200, 10,true,false,false,true,"","em","")'
root -l -q 'PlotNtupleVariables_ll_DataDrivenComplex.C("eta_1","eta_1", "Events",-2.5, 2.5, 10,true,false,false,true,"","em","")'
root -l -q 'PlotNtupleVariables_ll_DataDrivenComplex.C("eta_2","eta_2", "Events",-2.5, 2.5, 10,true,false,false,true,"","em","")'
root -l -q 'PlotNtupleVariables_ll_DataDrivenComplex.C("eta_3","eta_3", "Events",-2.5, 2.5, 10,true,false,false,true,"","em","")'
root -l -q 'PlotNtupleVariables_ll_DataDrivenComplex.C("eta_4","eta_4", "Events",-2.5, 2.5, 10,true,false,false,true,"","em","")'
root -l -q 'PlotNtupleVariables_ll_DataDrivenComplex.C("met","Missing ET [GeV]", "Events",0, 200, 10,true,false,false,true,"","em","")'

root -l -q 'PlotNtupleVariables_ll_DataDrivenComplex.C("m_vis","visible mass [GeV] ", "Events",0, 300, 20,true,false,false,true,"","et","")'
root -l -q 'PlotNtupleVariables_ll_DataDrivenComplex.C("mll","Z legs visible mass [GeV] ", "Events",60, 120, 10,true,false,false,true,"","et","")'
root -l -q 'PlotNtupleVariables_ll_DataDrivenComplex.C("pt_1","pT_1 [GeV] ", "Events",0, 200, 10,true,false,false,true,"","et","")'
root -l -q 'PlotNtupleVariables_ll_DataDrivenComplex.C("pt_2","pT_2 [GeV] ", "Events",0, 150, 10,true,false,false,true,"","et","")'
root -l -q 'PlotNtupleVariables_ll_DataDrivenComplex.C("pt_3","pT_3 [GeV] ", "Events",0, 200, 10,true,false,false,true,"","et","")'
root -l -q 'PlotNtupleVariables_ll_DataDrivenComplex.C("pt_4","pT_4 [GeV] ", "Events",0, 200, 10,true,false,false,true,"","et","")'
root -l -q 'PlotNtupleVariables_ll_DataDrivenComplex.C("eta_1","eta_1", "Events",-2.5, 2.5, 10,true,false,false,true,"","et","")'
root -l -q 'PlotNtupleVariables_ll_DataDrivenComplex.C("eta_2","eta_2", "Events",-2.5, 2.5, 10,true,false,false,true,"","et","")'
root -l -q 'PlotNtupleVariables_ll_DataDrivenComplex.C("eta_3","eta_3", "Events",-2.5, 2.5, 10,true,false,false,true,"","et","")'
root -l -q 'PlotNtupleVariables_ll_DataDrivenComplex.C("eta_4","eta_4", "Events",-2.5, 2.5, 10,true,false,false,true,"","et","")'
root -l -q 'PlotNtupleVariables_ll_DataDrivenComplex.C("met","Missing ET [GeV]", "Events",0, 200, 10,true,false,false,true,"","et","")'

root -l -q 'PlotNtupleVariables_ll_DataDrivenComplex.C("m_vis","visible mass [GeV] ", "Events",0, 300, 20,true,false,false,true,"","mt","")'
root -l -q 'PlotNtupleVariables_ll_DataDrivenComplex.C("mll","Z legs visible mass [GeV] ", "Events",60, 120, 10,true,false,false,true,"","mt","")'
root -l -q 'PlotNtupleVariables_ll_DataDrivenComplex.C("pt_1","pT_1 [GeV] ", "Events",0, 200, 10,true,false,false,true,"","mt","")'
root -l -q 'PlotNtupleVariables_ll_DataDrivenComplex.C("pt_2","pT_2 [GeV] ", "Events",0, 150, 10,true,false,false,true,"","mt","")'
root -l -q 'PlotNtupleVariables_ll_DataDrivenComplex.C("pt_3","pT_3 [GeV] ", "Events",0, 200, 10,true,false,false,true,"","mt","")'
root -l -q 'PlotNtupleVariables_ll_DataDrivenComplex.C("pt_4","pT_4 [GeV] ", "Events",0, 200, 10,true,false,false,true,"","mt","")'
root -l -q 'PlotNtupleVariables_ll_DataDrivenComplex.C("eta_1","eta_1", "Events",-2.5, 2.5, 10,true,false,false,true,"","mt","")'
root -l -q 'PlotNtupleVariables_ll_DataDrivenComplex.C("eta_2","eta_2", "Events",-2.5, 2.5, 10,true,false,false,true,"","mt","")'
root -l -q 'PlotNtupleVariables_ll_DataDrivenComplex.C("eta_3","eta_3", "Events",-2.5, 2.5, 10,true,false,false,true,"","mt","")'
root -l -q 'PlotNtupleVariables_ll_DataDrivenComplex.C("eta_4","eta_4", "Events",-2.5, 2.5, 10,true,false,false,true,"","mt","")'
root -l -q 'PlotNtupleVariables_ll_DataDrivenComplex.C("met","Missing ET [GeV]", "Events",0, 200, 10,true,false,false,true,"","mt","")'

root -l -q 'PlotNtupleVariables_ll_DataDrivenComplex.C("m_vis","visible mass [GeV] ", "Events",0, 300, 20,true,false,false,true,"","tt","")'
root -l -q 'PlotNtupleVariables_ll_DataDrivenComplex.C("mll","Z legs visible mass [GeV] ", "Events",60, 120, 10,true,false,false,true,"","tt","")'
root -l -q 'PlotNtupleVariables_ll_DataDrivenComplex.C("pt_1","pT_1 [GeV] ", "Events",0, 200, 10,true,false,false,true,"","tt","")'
root -l -q 'PlotNtupleVariables_ll_DataDrivenComplex.C("pt_2","pT_2 [GeV] ", "Events",0, 150, 10,true,false,false,true,"","tt","")'
root -l -q 'PlotNtupleVariables_ll_DataDrivenComplex.C("pt_3","pT_3 [GeV] ", "Events",0, 200, 10,true,false,false,true,"","tt","")'
root -l -q 'PlotNtupleVariables_ll_DataDrivenComplex.C("pt_4","pT_4 [GeV] ", "Events",0, 200, 10,true,false,false,true,"","tt","")'
root -l -q 'PlotNtupleVariables_ll_DataDrivenComplex.C("eta_1","eta_1", "Events",-2.5, 2.5, 10,true,false,false,true,"","tt","")'
root -l -q 'PlotNtupleVariables_ll_DataDrivenComplex.C("eta_2","eta_2", "Events",-2.5, 2.5, 10,true,false,false,true,"","tt","")'
root -l -q 'PlotNtupleVariables_ll_DataDrivenComplex.C("eta_3","eta_3", "Events",-2.5, 2.5, 10,true,false,false,true,"","tt","")'
root -l -q 'PlotNtupleVariables_ll_DataDrivenComplex.C("eta_4","eta_4", "Events",-2.5, 2.5, 10,true,false,false,true,"","tt","")'
root -l -q 'PlotNtupleVariables_ll_DataDrivenComplex.C("met","Missing ET [GeV]", "Events",0, 200, 10,true,false,false,true,"","tt","")'
