#!/bin/sh

./HTC_submit_seq.sh SynchNtupleProducer_AZh_mumu analysisMacro_AZh_mmet_Data.conf NTuples_SingleMuon_Run2017B 50
./HTC_submit_seq.sh SynchNtupleProducer_AZh_mumu analysisMacro_AZh_mmet_Data.conf NTuples_SingleMuon_Run2017C 50
./HTC_submit_seq.sh SynchNtupleProducer_AZh_mumu analysisMacro_AZh_mmet_Data.conf NTuples_SingleMuon_Run2017D 50
./HTC_submit_seq.sh SynchNtupleProducer_AZh_mumu analysisMacro_AZh_mmet_Data.conf NTuples_SingleMuon_Run2017E 50
./HTC_submit_seq.sh SynchNtupleProducer_AZh_mumu analysisMacro_AZh_mmet_Data.conf NTuples_SingleMuon_Run2017F 50

./HTC_submit_seq.sh SynchNtupleProducer_AZh_mumu analysisMacro_AZh_mmet_DY.conf NTuples_DYJetsToLL_M50 200
./HTC_submit_seq.sh SynchNtupleProducer_AZh_mumu analysisMacro_AZh_mmet_DY.conf NTuples_DYJetsToLL_M50_ext1 200

./HTC_submit_seq.sh SynchNtupleProducer_AZh_mumu analysisMacro_AZh_mmet_DY.conf NTuples_DY1JetsToLL_M50 200
./HTC_submit_seq.sh SynchNtupleProducer_AZh_mumu analysisMacro_AZh_mmet_DY.conf NTuples_DY2JetsToLL_M50 200
./HTC_submit_seq.sh SynchNtupleProducer_AZh_mumu analysisMacro_AZh_mmet_DY.conf NTuples_DY3JetsToLL_M50 200
./HTC_submit_seq.sh SynchNtupleProducer_AZh_mumu analysisMacro_AZh_mmet_DY.conf NTuples_DY4JetsToLL_M50 200

./HTC_submit_seq.sh SynchNtupleProducer_AZh_mumu analysisMacro_AZh_mmet_MC.conf NTuples_GluGluToContinToZZTo2e2mu 5
./HTC_submit_seq.sh SynchNtupleProducer_AZh_mumu analysisMacro_AZh_mmet_MC.conf NTuples_GluGluToContinToZZTo2e2tau 5
./HTC_submit_seq.sh SynchNtupleProducer_AZh_mumu analysisMacro_AZh_mmet_MC.conf NTuples_GluGluToContinToZZTo2mu2tau 5
./HTC_submit_seq.sh SynchNtupleProducer_AZh_mumu analysisMacro_AZh_mmet_MC.conf NTuples_GluGluToContinToZZTo4e 5
./HTC_submit_seq.sh SynchNtupleProducer_AZh_mumu analysisMacro_AZh_mmet_MC.conf NTuples_GluGluToContinToZZTo4mu 5
./HTC_submit_seq.sh SynchNtupleProducer_AZh_mumu analysisMacro_AZh_mmet_MC.conf NTuples_GluGluToContinToZZTo4tau 5

./HTC_submit_seq.sh SynchNtupleProducer_AZh_mumu analysisMacro_AZh_mmet_MC.conf NTuples_TTTo2L2Nu 100
./HTC_submit_seq.sh SynchNtupleProducer_AZh_mumu analysisMacro_AZh_mmet_MC.conf NTuples_TTToHadronic 100
./HTC_submit_seq.sh SynchNtupleProducer_AZh_mumu analysisMacro_AZh_mmet_MC.conf NTuples_TTToSemiLeptonic 100
./HTC_submit_seq.sh SynchNtupleProducer_AZh_mumu analysisMacro_AZh_mmet_MC.conf NTuples_TTWJetsToLNu 20
./HTC_submit_seq.sh SynchNtupleProducer_AZh_mumu analysisMacro_AZh_mmet_MC.conf NTuples_TTZJets 20

./HTC_submit_seq.sh SynchNtupleProducer_AZh_mumu analysisMacro_AZh_mmet_MC.conf NTuples_WWW_4F 40
./HTC_submit_seq.sh SynchNtupleProducer_AZh_mumu analysisMacro_AZh_mmet_MC.conf NTuples_WWW_4F_ext1 40
./HTC_submit_seq.sh SynchNtupleProducer_AZh_mumu analysisMacro_AZh_mmet_MC.conf NTuples_WWZ 20
./HTC_submit_seq.sh SynchNtupleProducer_AZh_mumu analysisMacro_AZh_mmet_MC.conf NTuples_WZZ 40
./HTC_submit_seq.sh SynchNtupleProducer_AZh_mumu analysisMacro_AZh_mmet_MC.conf NTuples_WZZ_ext 40
./HTC_submit_seq.sh SynchNtupleProducer_AZh_mumu analysisMacro_AZh_mmet_MC.conf NTuples_ZZZ 40
./HTC_submit_seq.sh SynchNtupleProducer_AZh_mumu analysisMacro_AZh_mmet_MC.conf NTuples_WZTo2Q2L_mllmin4p0_TuneCP5_13TeV-amcatnloFXFX-pythia8 40
./HTC_submit_seq.sh SynchNtupleProducer_AZh_mumu analysisMacro_AZh_mmet_MC.conf NTuples_WZTo3LNu 40
./HTC_submit_seq.sh SynchNtupleProducer_AZh_mumu analysisMacro_AZh_mmet_MC.conf NTuples_ZZTo2Q2L_mllmin4p0_TuneCP5_13TeV-amcatnloFXFX-pythia8 40
./HTC_submit_seq.sh SynchNtupleProducer_AZh_mumu analysisMacro_AZh_mmet_MC.conf NTuples_ZZTo4L 20

./HTC_submit_seq.sh SynchNtupleProducer_AZh_mumu analysisMacro_AZh_mmet_MC.conf NTuples_GluGluHToTauTau 40
./HTC_submit_seq.sh SynchNtupleProducer_AZh_mumu analysisMacro_AZh_mmet_MC.conf NTuples_VBFHToTauTau 40
./HTC_submit_seq.sh SynchNtupleProducer_AZh_mumu analysisMacro_AZh_mmet_MC.conf NTuples_WminusHToTauTau 40
./HTC_submit_seq.sh SynchNtupleProducer_AZh_mumu analysisMacro_AZh_mmet_MC.conf NTuples_WplusHToTauTau 40
./HTC_submit_seq.sh SynchNtupleProducer_AZh_mumu analysisMacro_AZh_mmet_MC.conf NTuples_ZHToTauTau_M125_CP5_13TeV-powheg-pythia8 20
./HTC_submit_seq.sh SynchNtupleProducer_AZh_mumu analysisMacro_AZh_mmet_MC.conf NTuples_ZHToTauTau_M125_CP5_13TeV-powheg-pythia8_ext1 20
./HTC_submit_seq.sh SynchNtupleProducer_AZh_mumu analysisMacro_AZh_mmet_MC.conf NTuples_ttHToTauTau 20

./HTC_submit_seq.sh SynchNtupleProducer_AZh_mumu analysisMacro_AZh_mmet_MC.conf NTuples_GluGluHToWWTo2L2Nu 40
./HTC_submit_seq.sh SynchNtupleProducer_AZh_mumu analysisMacro_AZh_mmet_MC.conf NTuples_VBFHToWWTo2L2Nu 40
./HTC_submit_seq.sh SynchNtupleProducer_AZh_mumu analysisMacro_AZh_mmet_MC.conf NTuples_HWminusJ_HToWW_M-125_TuneCP5_13TeV-powheg-jhugen727-pythia8 40
./HTC_submit_seq.sh SynchNtupleProducer_AZh_mumu analysisMacro_AZh_mmet_MC.conf NTuples_HWplusJ_HToWW_M-125_TuneCP5_13TeV-powheg-jhugen727-pythia8 40
./HTC_submit_seq.sh SynchNtupleProducer_AZh_mumu analysisMacro_AZh_mmet_MC.conf NTuples_HZJ_HToWWTo2L2Nu_ZTo2L_M-125_TuneCP5_13TeV-powheg-jhugen727-pythia8 20
./HTC_submit_seq.sh SynchNtupleProducer_AZh_mumu analysisMacro_AZh_mmet_MC.conf NTuples_GluGluZH_HToWW_ZTo2L_M125_13TeV_powheg_pythia8_TuneCP5_PSweights 20
./HTC_submit_seq.sh SynchNtupleProducer_AZh_mumu analysisMacro_AZh_mmet_MC.conf NTuples_GluGluHToZZTo4L_M125_TuneCP5_13TeV_powheg2_JHUGenV7011_pythia8 20

./HTC_submit_seq.sh SynchNtupleProducer_AZh_mumu analysisMacro_AZh_mmet_MC.conf NTuples_GluGluToAToZhToLLTauTau_M225_TuneCP5_13TeV-madgraph-pythia8 5
./HTC_submit_seq.sh SynchNtupleProducer_AZh_mumu analysisMacro_AZh_mmet_MC.conf NTuples_GluGluToAToZhToLLTauTau_M250_TuneCP5_13TeV-madgraph-pythia8 5
./HTC_submit_seq.sh SynchNtupleProducer_AZh_mumu analysisMacro_AZh_mmet_MC.conf NTuples_GluGluToAToZhToLLTauTau_M275_TuneCP5_13TeV-madgraph-pythia8 5
./HTC_submit_seq.sh SynchNtupleProducer_AZh_mumu analysisMacro_AZh_mmet_MC.conf NTuples_GluGluToAToZhToLLTauTau_M300_TuneCP5_13TeV-madgraph-pythia8 5
./HTC_submit_seq.sh SynchNtupleProducer_AZh_mumu analysisMacro_AZh_mmet_MC.conf NTuples_GluGluToAToZhToLLTauTau_M325_TuneCP5_13TeV-madgraph-pythia8 5
./HTC_submit_seq.sh SynchNtupleProducer_AZh_mumu analysisMacro_AZh_mmet_MC.conf NTuples_GluGluToAToZhToLLTauTau_M350_TuneCP5_13TeV-madgraph-pythia8 5
./HTC_submit_seq.sh SynchNtupleProducer_AZh_mumu analysisMacro_AZh_mmet_MC.conf NTuples_GluGluToAToZhToLLTauTau_M375_TuneCP5_13TeV-madgraph-pythia8 5
./HTC_submit_seq.sh SynchNtupleProducer_AZh_mumu analysisMacro_AZh_mmet_MC.conf NTuples_GluGluToAToZhToLLTauTau_M400_TuneCP5_13TeV-madgraph-pythia8 5
./HTC_submit_seq.sh SynchNtupleProducer_AZh_mumu analysisMacro_AZh_mmet_MC.conf NTuples_GluGluToAToZhToLLTauTau_M450_TuneCP5_13TeV-madgraph-pythia8 5
./HTC_submit_seq.sh SynchNtupleProducer_AZh_mumu analysisMacro_AZh_mmet_MC.conf NTuples_GluGluToAToZhToLLTauTau_M500_TuneCP5_13TeV-madgraph-pythia8 5
./HTC_submit_seq.sh SynchNtupleProducer_AZh_mumu analysisMacro_AZh_mmet_MC.conf NTuples_GluGluToAToZhToLLTauTau_M600_TuneCP5_13TeV-madgraph-pythia8 5
./HTC_submit_seq.sh SynchNtupleProducer_AZh_mumu analysisMacro_AZh_mmet_MC.conf NTuples_GluGluToAToZhToLLTauTau_M700_TuneCP5_13TeV-madgraph-pythia8 5
./HTC_submit_seq.sh SynchNtupleProducer_AZh_mumu analysisMacro_AZh_mmet_MC.conf NTuples_GluGluToAToZhToLLTauTau_M750_TuneCP5_13TeV-madgraph-pythia8 5
./HTC_submit_seq.sh SynchNtupleProducer_AZh_mumu analysisMacro_AZh_mmet_MC.conf NTuples_GluGluToAToZhToLLTauTau_M800_TuneCP5_13TeV-madgraph-pythia8 5
./HTC_submit_seq.sh SynchNtupleProducer_AZh_mumu analysisMacro_AZh_mmet_MC.conf NTuples_GluGluToAToZhToLLTauTau_M900_TuneCP5_13TeV-madgraph-pythia8 5
./HTC_submit_seq.sh SynchNtupleProducer_AZh_mumu analysisMacro_AZh_mmet_MC.conf NTuples_GluGluToAToZhToLLTauTau_M1000_TuneCP5_13TeV-madgraph-pythia8 5
./HTC_submit_seq.sh SynchNtupleProducer_AZh_mumu analysisMacro_AZh_mmet_MC.conf NTuples_GluGluToAToZhToLLTauTau_M1200_TuneCP5_13TeV-madgraph-pythia8 5
./HTC_submit_seq.sh SynchNtupleProducer_AZh_mumu analysisMacro_AZh_mmet_MC.conf NTuples_GluGluToAToZhToLLTauTau_M1400_TuneCP5_13TeV-madgraph-pythia8 5
./HTC_submit_seq.sh SynchNtupleProducer_AZh_mumu analysisMacro_AZh_mmet_MC.conf NTuples_GluGluToAToZhToLLTauTau_M1600_TuneCP5_13TeV-madgraph-pythia8 5
./HTC_submit_seq.sh SynchNtupleProducer_AZh_mumu analysisMacro_AZh_mmet_MC.conf NTuples_GluGluToAToZhToLLTauTau_M1800_TuneCP5_13TeV-madgraph-pythia8 5
./HTC_submit_seq.sh SynchNtupleProducer_AZh_mumu analysisMacro_AZh_mmet_MC.conf NTuples_GluGluToAToZhToLLTauTau_M2000_TuneCP5_13TeV-madgraph-pythia8 5

./HTC_submit_seq.sh SynchNtupleProducer_AZh_mumu analysisMacro_AZh_mmet_MC.conf NTuples_BBAToZhToLLTauTau_M225_TuneCP5_13TeV-madgraph-pythia8 5
./HTC_submit_seq.sh SynchNtupleProducer_AZh_mumu analysisMacro_AZh_mmet_MC.conf NTuples_BBAToZhToLLTauTau_M250_TuneCP5_13TeV-madgraph-pythia8 5
./HTC_submit_seq.sh SynchNtupleProducer_AZh_mumu analysisMacro_AZh_mmet_MC.conf NTuples_BBAToZhToLLTauTau_M275_TuneCP5_13TeV-madgraph-pythia8 5
./HTC_submit_seq.sh SynchNtupleProducer_AZh_mumu analysisMacro_AZh_mmet_MC.conf NTuples_BBAToZhToLLTauTau_M300_TuneCP5_13TeV-madgraph-pythia8 5
./HTC_submit_seq.sh SynchNtupleProducer_AZh_mumu analysisMacro_AZh_mmet_MC.conf NTuples_BBAToZhToLLTauTau_M325_TuneCP5_13TeV-madgraph-pythia8 5
./HTC_submit_seq.sh SynchNtupleProducer_AZh_mumu analysisMacro_AZh_mmet_MC.conf NTuples_BBAToZhToLLTauTau_M350_TuneCP5_13TeV-madgraph-pythia8 5
./HTC_submit_seq.sh SynchNtupleProducer_AZh_mumu analysisMacro_AZh_mmet_MC.conf NTuples_BBAToZhToLLTauTau_M375_TuneCP5_13TeV-madgraph-pythia8 5
./HTC_submit_seq.sh SynchNtupleProducer_AZh_mumu analysisMacro_AZh_mmet_MC.conf NTuples_BBAToZhToLLTauTau_M400_TuneCP5_13TeV-madgraph-pythia8 5
./HTC_submit_seq.sh SynchNtupleProducer_AZh_mumu analysisMacro_AZh_mmet_MC.conf NTuples_BBAToZhToLLTauTau_M450_TuneCP5_13TeV-madgraph-pythia8 5
./HTC_submit_seq.sh SynchNtupleProducer_AZh_mumu analysisMacro_AZh_mmet_MC.conf NTuples_BBAToZhToLLTauTau_M500_TuneCP5_13TeV-madgraph-pythia8 5
./HTC_submit_seq.sh SynchNtupleProducer_AZh_mumu analysisMacro_AZh_mmet_MC.conf NTuples_BBAToZhToLLTauTau_M600_TuneCP5_13TeV-madgraph-pythia8 5
./HTC_submit_seq.sh SynchNtupleProducer_AZh_mumu analysisMacro_AZh_mmet_MC.conf NTuples_BBAToZhToLLTauTau_M700_TuneCP5_13TeV-madgraph-pythia8 5
./HTC_submit_seq.sh SynchNtupleProducer_AZh_mumu analysisMacro_AZh_mmet_MC.conf NTuples_BBAToZhToLLTauTau_M750_TuneCP5_13TeV-madgraph-pythia8 5
./HTC_submit_seq.sh SynchNtupleProducer_AZh_mumu analysisMacro_AZh_mmet_MC.conf NTuples_BBAToZhToLLTauTau_M800_TuneCP5_13TeV-madgraph-pythia8 5
./HTC_submit_seq.sh SynchNtupleProducer_AZh_mumu analysisMacro_AZh_mmet_MC.conf NTuples_BBAToZhToLLTauTau_M900_TuneCP5_13TeV-madgraph-pythia8 5
./HTC_submit_seq.sh SynchNtupleProducer_AZh_mumu analysisMacro_AZh_mmet_MC.conf NTuples_BBAToZhToLLTauTau_M1000_TuneCP5_13TeV-madgraph-pythia8 5
./HTC_submit_seq.sh SynchNtupleProducer_AZh_mumu analysisMacro_AZh_mmet_MC.conf NTuples_BBAToZhToLLTauTau_M1200_TuneCP5_13TeV-madgraph-pythia8 5
./HTC_submit_seq.sh SynchNtupleProducer_AZh_mumu analysisMacro_AZh_mmet_MC.conf NTuples_BBAToZhToLLTauTau_M1400_TuneCP5_13TeV-madgraph-pythia8 5
./HTC_submit_seq.sh SynchNtupleProducer_AZh_mumu analysisMacro_AZh_mmet_MC.conf NTuples_BBAToZhToLLTauTau_M1600_TuneCP5_13TeV-madgraph-pythia8 5
./HTC_submit_seq.sh SynchNtupleProducer_AZh_mumu analysisMacro_AZh_mmet_MC.conf NTuples_BBAToZhToLLTauTau_M1800_TuneCP5_13TeV-madgraph-pythia8 5
./HTC_submit_seq.sh SynchNtupleProducer_AZh_mumu analysisMacro_AZh_mmet_MC.conf NTuples_BBAToZhToLLTauTau_M2000_TuneCP5_13TeV-madgraph-pythia8 5
