#!/bin/sh

./HTC_submit_seq.sh SynchNtupleProducer_AZh_mumu analysisMacro_AZh_mmt_Data.conf NTuples_SingleMuon_Run2017B 100
./HTC_submit_seq.sh SynchNtupleProducer_AZh_mumu analysisMacro_AZh_mmt_Data.conf NTuples_SingleMuon_Run2017C 100
./HTC_submit_seq.sh SynchNtupleProducer_AZh_mumu analysisMacro_AZh_mmt_Data.conf NTuples_SingleMuon_Run2017D 100
./HTC_submit_seq.sh SynchNtupleProducer_AZh_mumu analysisMacro_AZh_mmt_Data.conf NTuples_SingleMuon_Run2017E 100
./HTC_submit_seq.sh SynchNtupleProducer_AZh_mumu analysisMacro_AZh_mmt_Data.conf NTuples_SingleMuon_Run2017F 100

./HTC_submit_seq.sh SynchNtupleProducer_AZh_mumu analysisMacro_AZh_mmt_DY.conf NTuples_DYJetsToLL_M50 200
./HTC_submit_seq.sh SynchNtupleProducer_AZh_mumu analysisMacro_AZh_mmt_DY.conf NTuples_DYJetsToLL_M50_ext1 200

./HTC_submit_seq.sh SynchNtupleProducer_AZh_mumu analysisMacro_AZh_mmt_DY.conf NTuples_DY1JetsToLL_M50 200
./HTC_submit_seq.sh SynchNtupleProducer_AZh_mumu analysisMacro_AZh_mmt_DY.conf NTuples_DY2JetsToLL_M50 200
./HTC_submit_seq.sh SynchNtupleProducer_AZh_mumu analysisMacro_AZh_mmt_DY.conf NTuples_DY3JetsToLL_M50 200
./HTC_submit_seq.sh SynchNtupleProducer_AZh_mumu analysisMacro_AZh_mmt_DY.conf NTuples_DY4JetsToLL_M50 200

./HTC_submit_seq.sh SynchNtupleProducer_AZh_mumu analysisMacro_AZh_mmt_MC.conf NTuples_GluGluToContinToZZTo2e2mu 200
./HTC_submit_seq.sh SynchNtupleProducer_AZh_mumu analysisMacro_AZh_mmt_MC.conf NTuples_GluGluToContinToZZTo2e2tau 200
./HTC_submit_seq.sh SynchNtupleProducer_AZh_mumu analysisMacro_AZh_mmt_MC.conf NTuples_GluGluToContinToZZTo2mu2tau 200
./HTC_submit_seq.sh SynchNtupleProducer_AZh_mumu analysisMacro_AZh_mmt_MC.conf NTuples_GluGluToContinToZZTo4e 200
./HTC_submit_seq.sh SynchNtupleProducer_AZh_mumu analysisMacro_AZh_mmt_MC.conf NTuples_GluGluToContinToZZTo4mu 200
./HTC_submit_seq.sh SynchNtupleProducer_AZh_mumu analysisMacro_AZh_mmt_MC.conf NTuples_GluGluToContinToZZTo4tau 200

./HTC_submit_seq.sh SynchNtupleProducer_AZh_mumu analysisMacro_AZh_mmt_MC.conf NTuples_TTTo2L2Nu 200
./HTC_submit_seq.sh SynchNtupleProducer_AZh_mumu analysisMacro_AZh_mmt_MC.conf NTuples_TTToHadronic 200
./HTC_submit_seq.sh SynchNtupleProducer_AZh_mumu analysisMacro_AZh_mmt_MC.conf NTuples_TTToSemiLeptonic 200
./HTC_submit_seq.sh SynchNtupleProducer_AZh_mumu analysisMacro_AZh_mmt_MC.conf NTuples_TTWJetsToLNu 200
./HTC_submit_seq.sh SynchNtupleProducer_AZh_mumu analysisMacro_AZh_mmt_MC.conf NTuples_TTZJets 200

./HTC_submit_seq.sh SynchNtupleProducer_AZh_mumu analysisMacro_AZh_mmt_MC.conf NTuples_WWW_4F 100
./HTC_submit_seq.sh SynchNtupleProducer_AZh_mumu analysisMacro_AZh_mmt_MC.conf NTuples_WWW_4F_ext1 100
./HTC_submit_seq.sh SynchNtupleProducer_AZh_mumu analysisMacro_AZh_mmt_MC.conf NTuples_WWZ 100
./HTC_submit_seq.sh SynchNtupleProducer_AZh_mumu analysisMacro_AZh_mmt_MC.conf NTuples_WZZ 100
./HTC_submit_seq.sh SynchNtupleProducer_AZh_mumu analysisMacro_AZh_mmt_MC.conf NTuples_WZZ_ext 100
./HTC_submit_seq.sh SynchNtupleProducer_AZh_mumu analysisMacro_AZh_mmt_MC.conf NTuples_ZZZ 100
./HTC_submit_seq.sh SynchNtupleProducer_AZh_mumu analysisMacro_AZh_mmt_MC.conf NTuples_WZTo2Q2L_mllmin4p0_TuneCP5_13TeV-amcatnloFXFX-pythia8 100
./HTC_submit_seq.sh SynchNtupleProducer_AZh_mumu analysisMacro_AZh_mmt_MC.conf NTuples_WZTo3LNu 100
./HTC_submit_seq.sh SynchNtupleProducer_AZh_mumu analysisMacro_AZh_mmt_MC.conf NTuples_ZZTo2Q2L_mllmin4p0_TuneCP5_13TeV-amcatnloFXFX-pythia8 100
./HTC_submit_seq.sh SynchNtupleProducer_AZh_mumu analysisMacro_AZh_mmt_MC.conf NTuples_ZZTo4L 100

./HTC_submit_seq.sh SynchNtupleProducer_AZh_mumu analysisMacro_AZh_mmt_MC.conf NTuples_GluGluHToTauTau 100
./HTC_submit_seq.sh SynchNtupleProducer_AZh_mumu analysisMacro_AZh_mmt_MC.conf NTuples_VBFHToTauTau 100
./HTC_submit_seq.sh SynchNtupleProducer_AZh_mumu analysisMacro_AZh_mmt_MC.conf NTuples_WminusHToTauTau 100
./HTC_submit_seq.sh SynchNtupleProducer_AZh_mumu analysisMacro_AZh_mmt_MC.conf NTuples_WplusHToTauTau 100
./HTC_submit_seq.sh SynchNtupleProducer_AZh_mumu analysisMacro_AZh_mmt_MC.conf NTuples_ZHToTauTau_M125_CP5_13TeV-powheg-pythia8 100
./HTC_submit_seq.sh SynchNtupleProducer_AZh_mumu analysisMacro_AZh_mmt_MC.conf NTuples_ZHToTauTau_M125_CP5_13TeV-powheg-pythia8_ext1 100
./HTC_submit_seq.sh SynchNtupleProducer_AZh_mumu analysisMacro_AZh_mmt_MC.conf NTuples_ttHToTauTau 100

./HTC_submit_seq.sh SynchNtupleProducer_AZh_mumu analysisMacro_AZh_mmt_MC.conf NTuples_GluGluHToWWTo2L2Nu 100
./HTC_submit_seq.sh SynchNtupleProducer_AZh_mumu analysisMacro_AZh_mmt_MC.conf NTuples_VBFHToWWTo2L2Nu 100
./HTC_submit_seq.sh SynchNtupleProducer_AZh_mumu analysisMacro_AZh_mmt_MC.conf NTuples_HWminusJ_HToWW_M-125_TuneCP5_13TeV-powheg-jhugen727-pythia8 100
./HTC_submit_seq.sh SynchNtupleProducer_AZh_mumu analysisMacro_AZh_mmt_MC.conf NTuples_HWplusJ_HToWW_M-125_TuneCP5_13TeV-powheg-jhugen727-pythia8 100
./HTC_submit_seq.sh SynchNtupleProducer_AZh_mumu analysisMacro_AZh_mmt_MC.conf NTuples_HZJ_HToWWTo2L2Nu_ZTo2L_M-125_TuneCP5_13TeV-powheg-jhugen727-pythia8 100
./HTC_submit_seq.sh SynchNtupleProducer_AZh_mumu analysisMacro_AZh_mmt_MC.conf NTuples_GluGluZH_HToWW_ZTo2L_M125_13TeV_powheg_pythia8_TuneCP5_PSweights 100
./HTC_submit_seq.sh SynchNtupleProducer_AZh_mumu analysisMacro_AZh_mmt_MC.conf NTuples_GluGluHToZZTo4L_M125_TuneCP5_13TeV_powheg2_JHUGenV7011_pythia8 100
